function displayAverageCounts(allData)
%%% Display the average counts per channels

disp(['Ch 0: ' num2str(mean(allData(1,:)),'%e') ...
    ' +- ' num2str(std(allData(1,:)),'%e')])
disp(['Ch 1: ' num2str(mean(allData(2,:)),'%e') ...
    ' +- ' num2str(std(allData(2,:)),'%e')])
disp(['Ch 2: ' num2str(mean(allData(3,:)),'%e') ...
    ' +- ' num2str(std(allData(3,:)),'%e')])
disp(['Ch 3: ' num2str(mean(allData(4,:)),'%e') ...
    ' +- ' num2str(std(allData(4,:)),'%e')])
end
